from django.urls import path
from .views import (
    test_view, 
    UserRegistrationView, 
    user_login, 
    ProductListAPIView, 
    HomePageProductListAPIView, 
    cheapest_products,
    cheapest_products_per_category,
    search_products,
    FavoriteCartListCreateView,
    DeleteFavoriteCartView,
    MarketsListAPIView,
    DiscountedProductsAPIView,
    UserInfoView,
    UserAddressView,
    ChangePasswordView,
    DeleteAccountView,
    ForgotPasswordView,
    ResetPasswordView,
    get_shopping_lists,
    create_shopping_list,
    get_shopping_list_details,
    delete_shopping_list,
    get_shopping_list_items,
    add_shopping_list_item,
    toggle_item_status,
    delete_shopping_list_item,
    add_member_to_list,
    respond_to_invitation,
    get_pending_invitations,
    NearbyMarketsWithPricesAPIView
)
from . import views



urlpatterns = [
    path('test/', test_view, name='test'),
    path('users/register/', UserRegistrationView.as_view(), name='register'),
    path('users/login/', user_login, name='login'),
    path('products/', ProductListAPIView.as_view(), name='product-list'),
    path('products/filtered/', HomePageProductListAPIView.as_view(), name='filtered-product-list'),
    path('cheapest-products/', views.cheapest_products, name='cheapest-products'),
    path('cheapest-products-per-category/', views.cheapest_products_per_category, name='cheapest-products-per-category'),
    path('cheapest-products-by-categories/', views.cheapest_products_by_categories, name='cheapest-products-by-categories'),
    path('search/', views.search_products, name='search_products'), # verilerin tablodan çekilebilmesi için eklediğim endpoint
    path('favorite-carts/', FavoriteCartListCreateView.as_view(), name='favorite-carts'),
    path('markets-products/', MarketsListAPIView.as_view(), name='market-products'),
    path('discounted-products/', DiscountedProductsAPIView.as_view(), name='discounted-products'),
    path('addresses/', UserAddressView.as_view(), name='user-addresses'),
    path('addresses/<int:address_id>/', UserAddressView.as_view(), name='delete-address'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete-account'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('shopping-lists/', get_shopping_lists, name='get_shopping_lists'),
    path('shopping-lists/create/', create_shopping_list, name='create_shopping_list'),
    path('shopping-lists/<int:list_id>/', get_shopping_list_details, name='get_shopping_list_details'),
    path('shopping-lists/<int:list_id>/items/', get_shopping_list_items, name='get_shopping_list_items'),
    path('shopping-lists/<int:list_id>/items/add/', add_shopping_list_item, name='add_shopping_list_item'),
    path('shopping-lists/<int:list_id>/delete/', delete_shopping_list, name='delete_shopping_list'),
    path('shopping-lists/<int:list_id>/add-member/', add_member_to_list, name='add_member_to_list'),
    path('items/<int:item_id>/toggle/', toggle_item_status, name='toggle_item_status'),
    path('items/<int:item_id>/delete/', delete_shopping_list_item, name='delete_shopping_list_item'),
    path('invitations/respond/', respond_to_invitation, name='respond_to_invitation'),
    path('invitations/pending/', get_pending_invitations, name='get_pending_invitations'),
    path('favorite-carts/<int:pk>/', DeleteFavoriteCartView.as_view(), name='delete-favorite-cart'),
    path('user-info/', UserInfoView.as_view(), name='user-info'),
    path('nearby-markets/', NearbyMarketsWithPricesAPIView.as_view(), name='nearby-markets'),
]