# Generated by Django 5.1.4 on 2024-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
            ],
            options={
                'db_table': 'sample_data',
            },
        ),
    ]
