# Generated by Django 5.1.2 on 2025-03-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favoritecart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favoritecart',
            name='products',
        ),
        migrations.AlterField(
            model_name='favoritecart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FavoriteCartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('quantity', models.PositiveIntegerField()),
                ('favorite_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.favoritecart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_carts_products',
            },
        ),
    ]
