# Generated by Django 5.1.4 on 2025-04-03 09:57

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_favoritecart_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrefourProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrefour_products',
            },
        ),
        migrations.CreateModel(
            name='MarketpaketiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marketpaketi_products',
            },
        ),
        migrations.CreateModel(
            name='MigrosProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migros_products',
            },
        ),
        migrations.CreateModel(
            name='MopasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mopas_products',
            },
        ),
        migrations.CreateModel(
            name='SokmarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.TextField()),
                ('sub_category', models.TextField()),
                ('lowest_category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.TextField()),
                ('product_link', models.TextField()),
                ('page_link', models.TextField()),
                ('image_url', models.TextField()),
                ('date', models.TextField()),
                ('market_name', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sokmarket_products',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
